# Generated by Django 4.1.9 on 2023-06-23 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Single", "Single"),
                            ("EP", "EP"),
                            ("Album", "Album"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "album",
            },
        ),
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("short_description", models.TextField()),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("Pop", "Pop"),
                            ("Rock", "Rock"),
                            ("Metal", "Metal"),
                            ("Indie", "Indie"),
                            ("House", "House"),
                            ("Techno", "Techno"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "artist",
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                ("subscription_start", models.DateField(blank=True, null=True)),
                ("subscription_end", models.DateField(blank=True, null=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                "db_table": "user",
            },
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("lyrics", models.TextField(blank=True, null=True)),
                ("duration", models.CharField(max_length=5)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="music.album"
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="music.artist",
                    ),
                ),
            ],
            options={
                "db_table": "track",
            },
        ),
        migrations.AddField(
            model_name="album",
            name="artist",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music.artist",
            ),
        ),
    ]
